version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: local
    volumes:
      - ./src:/home/node/app/src
    container_name: api
    ports:
      - '3000:3000'
    command: npm run start:dev
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:13-alpine
    env_file:
      - .env
    container_name: api-postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  db:
