version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: local
    volumes:
      - ./src:/home/node/app/src:ro
      - /home/node/app/node_modules
    container_name: api
    ports:
      - '${PORT}:${PORT}'
      - '9229:9229'
    command: npm run start:debug
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:13-alpine
    env_file:
      - .env
    container_name: api-postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  db:
